variables:
    CURRENT_HW: "hw02"
    CURRENT_TEST: "testhw02"
    TEST_HASH_EXPECTED: "3b0aa1b76b5af9bf53b7642120fa5c55f3363de33ff02e89eeee42e161815000"

# pre-verify testing system hash
before_script:
  - tester="python3 -c 'import base64, lzma; exec(lzma.decompress(base64.b64decode(\"/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ANoAZpdAAUbSxPKKmVtGhRPQtvDy44ev3OIPm3q08xy0m1+Vzts/YuDUpfq1D15P9KyY1ltIZb4nnvSxakQAJy1iSkSn0CSwxAcZ9BdnVKenS6RtGMtxaPfI4+FwrOfdwPZUVPktXnaYcFn4bVa3hvnOJxmO4w8WujSjqrSI4IyI2j1d6dwwpL4qBlgvcn6q8B6KU/KbmlIgAAdpN7LNlBnEqIdk40AntOo9T78J0EcddwODxBjtMVoV2ClCj6u5kgg7/i9CaBoQz3deUx205aCsVgBvu8nQV/TZYnVSzIih59lrhlBmnijJ0wqfxzukLTWsFkOZWH1nxKlAlQsuRo37dzsJ6YAlfFvHwZEz/0p4jWSqATRPxq2af1QWvY7uebFtE2bJQUbvqK1u7f75ItWPMZI2ySib7iRN/X8eyBTrqLhWASCGbJVosnNs0aTSSXA3axFRqTSLg8tS2A/a/HnRZGTQvOiWXw3m7FMMxPWuAkOZSdhCz02leqZUghcY11NFRmgG7ji0rVPQsCqOUwJI9lnkR6evCqsPMx83RaSAAAAH2FED2Xm7QEAAbYD6QYAAGUsnOexxGf7AgAAAAAEWVo=\")).decode())'"
  - TEST_HASH=$(eval "$tester" . testing/ CMakeLists.txt)

  - echo $TEST_HASH
  - echo $TEST_HASH_EXPECTED
  - if [[ "$TEST_HASH" == "$TEST_HASH_EXPECTED" ]]; then echo "/CMakeLists.txt and testing/ folder are good!"; else echo "/CMakeLists or testing/ folder contents are not as expected!"; exit 1; fi


stages:
- compile
- test

# yaml template lol
.job_template: &build_job_artifact
  stage: compile
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build/

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build/
    expire_in: 30 mins


# compile jobs
build-gcc:
  <<: *build_job_artifact
  image: cpp/compiler:20
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make $CURRENT_HW ${CURRENT_TEST} -j4 VERBOSE=1
  tags:
    - linux

build-clang:
  <<: *build_job_artifact
  image: cpp/compiler:20
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-lc++abi"
    - make $CURRENT_HW ${CURRENT_TEST} -j4 VERBOSE=1
  tags:
    - linux


# test jobs
test-gcc:
  stage: test
  image: cpp/compiler:20
  script:
    - cd build
    - ctest -R $CURRENT_HW -V -O ctest.log
  dependencies:
    - build-gcc
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - build/ctest.log
    expire_in: 1 year
  tags:
    - linux

test-clang:
  stage: test
  image: cpp/compiler:20
  script:
    - cd build
    - ctest -R $CURRENT_HW -V -O ctest.log
  dependencies:
    - build-clang
  tags:
    - linux
